#!/bin/sh

function fix_whitespace {
  tmp=$(mktemp /tmp/fix-whitespace.XXXXX)
  git diff --cached --no-color > $tmp \
    && git apply --index -R $tmp \
    && git apply --index --whitespace=fix $tmp 2>/dev/null

  if git diff-index --quiet HEAD --; then
      echo "pre-commit: Nothing left to commit after fixing whitespace errors below"
      git apply --index $tmp 2>/dev/null
      git diff --check --cached
      rm $tmp
      return 1
  fi
}

fix_whitespace
